
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dhcho
 */
public class ProductService extends javax.swing.JFrame {

    private BufferedImage productImage = null;
    
    /**
     * Creates new form ProductService
     */
    public ProductService() {
        
        initComponents();

        getConnection();
    }

    public Connection getConnection()
    {
        String hostName = "ec2-54-163-240-54.compute-1.amazonaws.com";
        String dbName = "d89l9begjikklj";
        String userName = "isscllglmxgeln";
        String password = "334f696049572d4bc9c3b6b78c3410301e24dd3b5fd2b96dc15bf4c1c6fed113";

        Connection conn = null;

        try
        {
            Class.forName("org.postgresql.Driver");
            String url = "jdbc:postgresql://" + hostName + "/" + dbName + "?user=" + userName + "&password=" + password + "&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory";
            conn = DriverManager.getConnection(url);
            this.setTitle("Connected");
            return conn;
        }
        catch(Exception e)
        {
            System.out.println("Not Connected");
            return conn;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jtxtProductID1 = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jtxtPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtDesc = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        label6 = new java.awt.Label();
        jtxtStockQty = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        shallYouValidate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label1.setText("Desc");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        label2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label2.setText("Product ID");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        label3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label3.setText("Name");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        label4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label4.setText("Price");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jtxtProductID1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jtxtProductID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtProductID1ActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtProductID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 180, 60));

        jtxtName.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 240, 60));

        jtxtPrice.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jtxtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPriceActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 240, 60));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setText(" Choose Image...");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 240, 190));

        label5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label5.setText("Image");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jtxtDesc.setColumns(20);
        jtxtDesc.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jtxtDesc.setLineWrap(true);
        jtxtDesc.setRows(5);
        jtxtDesc.setAutoscrolls(false);
        jtxtDesc.setMinimumSize(new java.awt.Dimension(1000, 22));
        jScrollPane1.setViewportView(jtxtDesc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 1150, -1));

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Price", "Name", "Stock Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 204));
        jTable1.setOpaque(false);
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 360, 460));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, 150, 80));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 150, 80));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, -1, 80));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton4.setText("First");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 640, 150, 80));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton5.setText("Prev");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 640, -1, 80));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton6.setText("Last");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 640, 150, 80));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton7.setText("Next");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 640, 150, 80));

        label6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label6.setText("Stock Qty");
        jPanel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jtxtStockQty.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jtxtStockQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStockQtyActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtStockQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 120, 60));

        jPanel2.setBackground(java.awt.Color.orange);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Service");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel4.setForeground(java.awt.Color.red);
        jLabel4.setText("By Daniel Cho");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 330, 80, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 330, 370));

        shallYouValidate.setForeground(java.awt.Color.blue);
        jPanel1.add(shallYouValidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameActionPerformed

    private void jtxtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPriceActionPerformed

    private void jtxtProductID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtProductID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtProductID1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //INSERT

        boolean isValid = validateForm();
        
        if(isValid)
        {
            //insert into db...
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private boolean validateForm()
    {
        boolean validationRequired = false;
        shallYouValidate.setText("");

        String productID = jtxtProductID1.getText();
        if(productID.length() == 0)
        {
            jtxtProductID1.setForeground(Color.WHITE);
            jtxtProductID1.setBackground(Color.BLUE);
            validationRequired = true;
        }
        else
        {
            jtxtProductID1.setForeground(Color.BLACK);
            jtxtProductID1.setBackground(Color.WHITE);
        }

        String productName = jtxtName.getText();
        if(productName.length() == 0)
        {
            jtxtName.setForeground(Color.WHITE);
            jtxtName.setBackground(Color.BLUE);
            validationRequired = true;
        }
        else
        {
            jtxtName.setForeground(Color.BLACK);
            jtxtName.setBackground(Color.WHITE);
        }

        String productPrice = jtxtPrice.getText();
        if(productPrice.length() == 0)
        {
            jtxtPrice.setForeground(Color.WHITE);
            jtxtPrice.setBackground(Color.BLUE);
            validationRequired = true;
        }
        else
        {
            jtxtPrice.setForeground(Color.BLACK);
            jtxtPrice.setBackground(Color.WHITE);
        }

        String productDesc = jtxtDesc.getText();
        if(productDesc.length() == 0)
        {
            jtxtDesc.setForeground(Color.WHITE);
            jtxtDesc.setBackground(Color.BLUE);
            validationRequired = true;
        }
        else
        {
            jtxtDesc.setForeground(Color.BLACK);
            jtxtDesc.setBackground(Color.WHITE);
        }

        String productQty = jtxtStockQty.getText();
        if(productQty.length() == 0)
        {
            jtxtStockQty.setForeground(Color.WHITE);
            jtxtStockQty.setBackground(Color.BLUE);
            validationRequired = true;
        }
        else
        {
            jtxtStockQty.setForeground(Color.BLACK);
            jtxtStockQty.setBackground(Color.WHITE);
        }
        
        if(validationRequired)
        {
            shallYouValidate.setText("* PLEASE VALIDATE THE ONES IN BLUE..");
        }
        else
        {
            shallYouValidate.setText("");
        }
        
        return !validationRequired;
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jtxtStockQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStockQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStockQtyActionPerformed

    private ImageIcon resizeImage(BufferedImage b, int w, int h)
    {
        BufferedImage tempImg = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D gr = tempImg.createGraphics();
        
        gr.drawImage(b, 0, 0, w, h, null);
        gr.dispose();
        
        return new ImageIcon(tempImg);
    }
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        JFileChooser fc = new JFileChooser();
        int result = fc.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File file = fc.getSelectedFile();
            try
            {
                BufferedImage b = ImageIO.read(file);
                productImage = b;
                ImageIcon ii = resizeImage(b, jLabel1.getWidth(), jLabel1.getHeight());
                jLabel1.setIcon(ii);
            }
            catch(Exception e)
            {
            }
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jtxtDesc;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPrice;
    private javax.swing.JTextField jtxtProductID1;
    private javax.swing.JTextField jtxtStockQty;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private javax.swing.JLabel shallYouValidate;
    // End of variables declaration//GEN-END:variables
}
